title: Tech.Braineffect
email: mitxel.moriana@brain-effect.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech Blog
baseurl: ""
domain: brain-effect.github.io
url: "https://brain-effect.github.io"
instagram_username: mybraineffect
twitter_username: braineffect
github_username:  brain-effect
facebook_username: braineffect
linkedin_company: braineffect-performance-food
rss: true
destination: ./docs

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
